apiVersion: apps/v1
kind: Deployment
metadata:
  name: esempio-deployment-books
  namespace: lez01-intro
spec:
  replicas: 2                # Replica Set: 3 repliche del pod
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
      - name: book-container
        image: archety/books-api-in-memory:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"