# Layer 0 del sistema operativo - costruisce il container docker create...
FROM ubuntu:24.04

# Esecuzione libera del comando
RUN apt-get update && \
    apt-get install curl -y

# Entrypoint
CMD ["bash"]