apiVersion: v1
kind: ConfigMap
metadata:
  name: esempio-configmap
  namespace: lez02-configmap
data:
  APP_MESSAGE: "Benvenuto alla lezione sulle ConfigMap!"
  APP_VERSION: "1.0.0"
  APP_ENV: "production"