apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: lez02-configmap
spec:
  containers:
    - name: demo-container
      image: busybox:latest
      command: ["sh", "-c", "echo $APP_MES && echo Version: $APP_VERSION && echo Environment: $APP_ENV && sleep 3600"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      # Monta la ConfigMap come variabili d'ambiente
      env:
        - name: APP_MES
          valueFrom:
            configMapKeyRef:
              name: esempio-configmap
              key: APP_MESSAGE
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: esempio-configmap
              key: APP_VERSION
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: esempio-configmap
              key: APP_ENV